pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:todo-mudaston/nest-todo-api.git
          - cd nest-todo-api.git
          - git push --mirror git@github.com:mudaston/nest-todo-api.git