import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Header } from '@feature/header'

import { StoreProvider } from '@app/store'
import { ThemeProvider } from '@app/theme'

import '@app/bootstrap/normalize.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <StoreProvider>
                    <ThemeProvider>
                        <Header />
                        {children}
                    </ThemeProvider>
                </StoreProvider>
            </body>
        </html>
    )
}
